### ISSUE TITLE
PDF preimum problem

### ISSUE THREAD

**Issue by genefend** [j26design/PDF-Embedder-Premium#1]
I have a windows server which does not have a public_folder, which I did create and insert the files on the server which did not work so I installed both files to the root it did make the PDF image work, but it could not find the pdf. 
![image](https://cloud.githubusercontent.com/assets/19257410/15102022/72941c0e-1568-11e6-8db5-1b53cf96fe60.png)
I have attached a photo. I do have the free one installed and also purchased the and used the musethemes PDF. I liked your PDF from the demo. How can I get this to work?

**Comment by jp26jp** [comment]
Interesting, that's good to know. That image didn't upload. Can you try reuploading the image? Or, if you are able to, it would be helpful if you could temporarily upload a temporary page to your server.

**Comment by genefend** [comment]
Here is a link to the pdf that is not loading and the error I spoke about
http://surfacefinishequipment.com/surface-articles.html

**Comment by jp26jp** [comment]
Okay, I see what is going on. I'll get an update out for it today!

**Comment by jp26jp** [comment]
I just sent out the update that will fix this issue so I'm going to close this report. If the update doesn't fix the error, please reopen the report!
