### ISSUE TITLE
Too many PDF windows on a page / won't load?

### ISSUE THREAD

**Issue by jgoding** [j26design/PDF-Embedder-Premium#10]
Hi - I have a little challenge with a page that was working (with many of your PDF widgets on it) and wondering if you have had any experience with a maximum number of uses per page? When I was first applying your widget to this page it was working fine with around 5-7 single page PDF windows, now I have 24 and it works fine on the desktop and laptop platforms but the Iphone 6S (and also older Ipad) I have won't support it, I keep getting an error / re-loading message "A problem occurred with this webpage so it was reloaded) - but it never loads. Very annoying. I'm not sure if this is to do with them having less available RAM than my fast laptop & desktop machines? 

Should I split these PDF's onto separate pages of say max 5-10 per page? I'm keen not to make them into a multi-page PDF but could do this as a last resort, or as a short term solution. 

I look forward to your response.

**Comment by jp26jp** [comment]
This should be fixed in the most recent update.
