### ISSUE TITLE
Zoom Level

### ISSUE THREAD

**Issue by macintoshi** [j26design/PDF-Embedder-Premium#12]
Hi,
I know I set Zoom (%) to 0 (zero) to get Automatic Zoom working in my page. Is there any way to get Page Fit?

Best regards,

Toshi

**Comment by jp26jp** [comment]
The ability to set the zoom to Page Fit was added to the most recent update. Just redownload the files that were sent in the recent update.

**Comment by macintoshi** [comment]
Hello John,Yes, I did it and it works! Thank you so much!
Best regards,

Toshi
