### ISSUE TITLE
Background Shadow

### ISSUE THREAD

**Issue by RGPatterson** [j26design/PDF-Embedder-Premium#13]
I did a test with PDF Embedder 2.1.0 that showed me I could get a completely white background for PDF document.  Then I used 2.1.0 on 15 pages for my actual website and thought I had the settings exactly the same as the test, but I now have a shadow effect for the PDF page inside my box.

I'm attaching two screengrabs from Safari.  You an also view the actual pages at

pdftester.businesscatalyst.com  (see Page 3)
and
tdpwebsite.businesscatalyst.com (Navigate to any of the Press pages)

Can you think of any reason this would  have happened?  

Richard Patterson
richard@rgpost.com

![tester](https://cloud.githubusercontent.com/assets/12321147/23040088/d48e4806-f444-11e6-8ec5-820112b280af.jpg)
![website](https://cloud.githubusercontent.com/assets/12321147/23040089/d4c38d36-f444-11e6-85d3-aceab37806ca.jpg)

**Comment by jp26jp** [comment]
The way that the shadow is displayed is slightly different in the update which may have been why you didn't see it on V2.0.0. I will add a feature that allows you to customize/remove the shadow.

**Comment by RGPatterson** [comment]
Thanks. I thought I had tested the latest update and not gotten the shadow but perhaps I was still using the older build and web folders.

Richard Patterson
310-709-6786
Richard@rgpost.com

**Comment by jp26jp** [comment]
This feature was added to the last update. Just redownload the files that were sent in the recent email.

**Comment by RGPatterson** [comment]
I don’t know if you ever saw my feedback, but this feature does not work for me.  I select the option to make the shadow 0 and I still get the same shadow when I view the website on businesscatalyst.com

It’s not a huge deal, but it would be nice to be able to eliminate the shadow.

Thanks.

Richard Patterson
135 S Medio Drive
Los Angeles, CA 90049-3935
Home: 310 472-8065
Cell: 310-709-6786
richard@rgpost.com
