### ISSUE TITLE
The Widget does not work

### ISSUE THREAD

**Issue by akrug84** [j26design/PDF-Embedder-Premium#17]
Hi,
yesterday i bought the widget and the pdfs does not show up.

![image](https://user-images.githubusercontent.com/29298542/26962532-192b658e-4ce7-11e7-9977-ede9e5251863.png)

i simply added a pdf and made no changes at all.

Adobe MuseCC 2017.0

**Comment by jp26jp** [comment]
If that's all you did, then that's exactly why it's not working. [Watch this video](https://www.youtube.com/watch?v=U1mZrY7A1Hg)
