### ISSUE TITLE
Can´t Find File

### ISSUE THREAD

**Issue by peter2352** [j26design/PDF-Embedder-Premium#2]
I have installed PDF embedded Premium but the widget don´t find the PDF File. I have copied
the two Folder on the Server.

sorry for my english. i am a German Guy

Best Regards

**Comment by jp26jp** [comment]
What's the URL?

**Comment by genefend** [comment]
http://surfacefinishequipment.com/surface-articles.html

**Comment by jp26jp** [comment]
Okay, V1.1.0 uses a completely different method of finding the PDF. Let me know if this fixes the issue. I will leave this thread open until I hear back from you.

**Comment by genefend** [comment]
I have reloaded both on the server and the muse program it works after you preview the new updates but when you close the site then go back  it stops working. So there is still a problem.

**Comment by jp26jp** [comment]
You're using V1.1.0?

**Comment by jp26jp** [comment]
It's working for me. Tested in multiple browsers

**Comment by genefend** [comment]
Thanks it is working great now.

**Comment by jp26jp** [comment]
Awesome! I'm glad we were able to get it figured out. Thank you for your patience on this as well as providing the links! Don't hesitate to open another case if you come across any more issues.
