### ISSUE TITLE
Different font in viewing window!

### ISSUE THREAD

**Issue by Slyrfecso** [j26design/PDF-Embedder-Premium#20]
Dear Developer,

1.
I localised the problem, we are getting the problem only under Safari.
The font is different then what I see in Adobe Acrobat or in other browser.
Please check my PDF.
http://alexbutor.hu/alex_nursery-school-furniture_catalog.html

2. Any chance to use viewer in popup windows?
Thanks.

**Comment by jp26jp** [comment]
The font looks the same to me. What do you mean by it's different?

**Comment by Slyrfecso** [comment]
Hi,

I have token a screenshot and I hope it will help you.
The main headline is different, on the left you can see the fake font.
I don’t know what I did but after some minutes and some click the right font appeared.
Maybe font activity problem with Suitcase?

Thanks.










Csongor Fekete
Graphic Designer  I  3D Artist
mobile: +36 30 231 0332
e-mail: ifjfecso@t-online.hu <mailto:ifjfecso@t-online.hu>
skype: ifjfecso.home
web: www.csongorfekete.com <http://www.csongorfekete.com/>

**Comment by Slyrfecso** [comment]
Hi,

I have token a screenshot and I hope it will help you.
The main headline is different, on the left you can see the fake font.
I don’t know what I did but after some minutes and some click the right font appeared.
Maybe font activity problem with Suitcase?

Thanks.







Csongor Fekete
Graphic Designer  I  3D Artist
mobile: +36 30 231 0332
e-mail: info@csongorfekete.com
skype: ifjfecso.home
web: www.csongorfekete.com

**Comment by jp26jp** [comment]
Not seeing the screenshot.

**Comment by Slyrfecso** [comment]
Hi,

I have attached again as JPG and PDF.
Thanks.







Csongor Fekete
Graphic Designer  I  3D Artist
mobile: +36 30 231 0332
e-mail: ifjfecso@t-online.hu <mailto:ifjfecso@t-online.hu>
skype: ifjfecso.home
web: www.csongorfekete.com <http://www.csongorfekete.com/>

**Comment by jp26jp** [comment]
There's nothing here.
