### ISSUE TITLE
error

### ISSUE THREAD

**Issue by genefend** [j26design/PDF-Embedder-Premium#4]
It stopped working with the same error.
 PDF.js v1.3.91 (build: d1e83b5)
Message: file origin does not match viewer's

**Comment by jp26jp** [comment]
Which version of the widget are you using?

**Comment by genefend** [comment]
The last one you sent me


PDF Embedder (Premium)
Turns out that the last update did not entirely fix the issue. This update definitely will. Sorry for the confusion! If you're a Lifetime member, then this widget has already synced to your computer!
DOWNLOAD UPDATES 
Reporting Errors
Don't forget, if you ever find a bug, report it here, and I will get it taken care of as soon as possible!

**Comment by jp26jp** [comment]
I'm closing this duplicate issue. [Get updates here](https://github.com/j26design/PDF-Embedder-Premium/issues/2).
