### ISSUE TITLE
Vanity url seems to break PDF viewer

### ISSUE THREAD

**Issue by mick-wieland** [j26design/PDF-Embedder-Premium#5]
Hi John,

When I use the Premium PDF embedder, it works fine on my site EXCEPT when I'm trying to view the site through a vanity url. The viewer seems to be unable to locate the file through the vanity url.

View these screenshots to see what I mean:
**Native url:** 
https://www.dropbox.com/s/3yke98if10ps5fv/Screen%20Shot%202016-08-12%20at%2011.27.02%20AM.png?dl=0

**Vanity url:** 
https://www.dropbox.com/s/kb1uywqo49yf5j5/Screen%20Shot%202016-08-12%20at%2011.30.16%20AM.png?dl=0

Any way to fix this?

**Comment by jp26jp** [comment]
Are these site's being hosted on business catalyst?

**Comment by mick-wieland** [comment]
No, godaddy hosting

**Comment by mick-wieland** [comment]
Exact urls should be visible on the screenshots.

**Comment by jp26jp** [comment]
Okay and are you uploading the site to the 2 locations with the same file?

**Comment by jp26jp** [comment]
Can you [upload the file here](https://www.dropbox.com/sh/d3oy2fsh9wtvspo/AADVi0Q6p-SoEANEGjVGtt3Za?dl=0)?

**Comment by mick-wieland** [comment]
Uploading to one location. Then I  set up an add-on domain in godaddy for the vanity url. The PDF will not display through to the vanity url.

**Comment by mick-wieland** [comment]
I can on Monday when I'm back in the office.

**Comment by jp26jp** [comment]
Vanity URLs (URL shorteners) aren't supposed to be accessed. They're supposed to redirect to where the page is located. If they don't they're bad for SEO. Are you sure you have it set up correctly?

**Comment by mick-wieland** [comment]
Yes, definitely set up correctly.

No worries, I switched the widget to your non-premium PDF embedder and that works fine. I can live without the extra control features. 

Vanity url:
http://itendswithusbook.com/#excerpt <http://itendswithusbook.com/#excerpt>

Native url:
http://www.simonandschusterpublishing.com/it-ends-with-us-colleen-hoover/index.html#excerpt <http://www.simonandschusterpublishing.com/it-ends-with-us-colleen-hoover/index.html#excerpt>

Thanks anyway!

Mick
