### ISSUE TITLE
PDF Viewer not fully built

### ISSUE THREAD

**Issue by museq** [j26design/PDF-Embedder-Premium#7]
Hello, Im really excited about this widget but I cant seem to get the PDF embedder to fully display. What I mean is I can see the frame of the of the PDF embedder but its not fully built. Its just grey without any of the buttons displayed as well as my PDF file is not displayed. Help Please!
Thanks 
![screenshot 2016-09-30 19 47 21](https://cloud.githubusercontent.com/assets/22554737/19011454/52f2ef70-874a-11e6-8826-0d097548ff71.png)
![screenshot 2016-09-30 19 48 01](https://cloud.githubusercontent.com/assets/22554737/19011455/5d12d484-874a-11e6-92da-5096f0336dc9.png)
![screenshot 2016-09-30 19 47 48](https://cloud.githubusercontent.com/assets/22554737/19011456/62693fea-874a-11e6-839f-1bc6089529db.png)

**Comment by jp26jp** [comment]
What is the URL?

**Comment by museq** [comment]
museq.me

**Comment by museq** [comment]
sorry its this one

http://museq.me/contributors.html
